### ISSUE TITLE
on blur event, cambia el valor del rut

### ISSUE THREAD

**Issue by Martiixx** [platanus/vue-dni#12]
Estimados:
Tengo el siguiente problema, al momento de hacer el input del rut, este valida y enmascara el rut correctamente, pero al momento de sacar el foco del input cambia la mascara del dato.
la llamada a v-rut no enmascara al momento de sacar el foco del input, pero si lo hace la llamada v-rut:live

![imagen](https://user-images.githubusercontent.com/23131106/46630854-dd2bf080-cb1b-11e8-8544-e20b7d4a9107.png)

la salida al lado izquierdo de la imagen estoy mostrando los valores que ingresan al metodo que maneja el input y por alguna razón al sacar de foco sobreescribe el valor newVal por oldVal.

![imagen](https://user-images.githubusercontent.com/23131106/46630548-e49eca00-cb1a-11e8-80b0-36d3260aa9a4.png)

mi configuración de vue-dni:

![imagen](https://user-images.githubusercontent.com/23131106/46630600-0e57f100-cb1b-11e8-95c5-d4957a558263.png)
![imagen](https://user-images.githubusercontent.com/23131106/46630616-1d3ea380-cb1b-11e8-82a5-ef3ba2cf5fa4.png)
![imagen](https://user-images.githubusercontent.com/23131106/46630676-3f382600-cb1b-11e8-8356-dbfabd7b5f2b.png)

vuelvo a recalcar que la validación del rut es correcta, solo el formato del valor es el que cambia y lo muestra de manera erronea.

Saludos y gracias!

**Comment by ellecito** [comment]
Tengo el mismo error. ¿Encontraste alguna solución?

**Comment by Martiixx** [comment]
Al final no pude resolver el problema, pero lo que si hice fue extraer el metodo que se encarga de hacer la validacion y la mascara del rut e implementarlo directamente como un metodo en donde lo utilizo.
Aqui hice un ejemplo de la implementación que hice en base al codigo de platanus. https://github.com/Martiixx/VueRut/blob/master/ruti.vue
Espero te sirva
Saludos

**Comment by dimitrycastex** [comment]
Por lo que veo el problema es cuando se usa un elemento que no es el **input** "puro" de html (como en el caso de @Martiixx que usa **fg-input** y en mi caso que me pasó lo mismo utilizando [v-text-field](https://vuetifyjs.com/en/components/text-fields/#text-fields) de [vuetify](https://vuetifyjs.com/en/)) para tener más datos acerca de este problema.

Saludos!
